---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[maven_deploy_integration_test::default]
    attributes:
      maven_deploy:
        repositories:
          central: https://repo1.maven.org/maven2
      
  - name: checksum_error
    run_list:
      - recipe[maven_deploy_integration_test::fake_maven_repository]
      - recipe[maven_deploy_integration_test::default]
    attributes:
      maven_deploy:
        repositories:
          central: http://127.0.0.1/maven2
      maven_deploy_integration_test:
        validate_checksum: true
        ignore_failure: true
